<?php

namespace TorMorten\Mix\Resolvers;

/**
 * Resolves assets built by Vite via the vite-manifest.json generated by
 * the zymfonix/dev viteManifestPlugin. The manifest format mirrors Laravel
 * Mix's mix-manifest.json so the existing MixController and cache layer
 * require no changes.
 *
 * Sits before ResolveLocal in all resolver chains so Vite-migrated modules
 * are resolved here while Mix modules fall through to ResolveLocal.
 */
class ResolveVite extends ResolveLocal
{
    protected function getManifest($params): array
    {
        try {
            $path = $this->getFilePath($params, 'vite-manifest.json');
            $manifest = file_get_contents($path);

            return json_decode($manifest, true) ?? [];
        } catch (\Exception $e) {
            return [];
        }
    }
}
